#!/usr/bin/env python3
# generated by clawhub on 2026-03-30
# this file is managed by clawhub and should not be edited directly
import os
import sys

# add workspace to path
workspace_dir = "/home/openclaw/.openclaw/workspace"
if workspace_dir not in sys.path:
    sys.path.insert(0, workspace_dir)

# import the actual script
from multi_wechat_hospitals.templates.wechat_fetch_hospital import main

if __name__ == "__main__":
    main()
